### ISSUE TITLE
AdminLTE 3.0 Tasks

### ISSUE THREAD

**Issue by almasaeed2010** [almasaeed2010/AdminLTE#771]
### Introduction
The tasks list we provide here contains the steps we will take to support BS4. It will also contain suggestions that have been approved. The list will grow as suggestions are added.

### Tasks List
- [x] Create branch for v3 development
- [ ] Using Bower, get all plugins
- [x] Convert AdminLTE LESS files to SCSS
- [x] Create a Grunt task to compile SASS
- [x] Include Bootstrap 4 in AdminLTE
- [ ] BS4 components that require upgrading:
 - [ ] Tables
 - [ ] Forms
 - [ ] navs
 - [ ] Pager
 - [ ] Carousel
 - [ ] Progress bars
- [ ] New BS4 components to support:
 - [ ] Cards
 - [ ] New navbar
- [ ] Rewrite all AdminLTE plugins in ECMA6
 - [x] Layout
 - [ ] Treeview
 - [x] PushMenu
 - [ ] Widget

I will add the approved features and enhancements here once we are done upgrading components to support BS4.

**Comment by crperlin** [comment]
**new feature(Hope)**:
1. add **gulpfile.js** auto constructor;
2. html constructor user `flexbox` [eg: sidebar-list , header-nav-responsive];
3. add more reset and more mobile meta , eg [ `-webkit-appearance:none `, `-ms-overflow-style: scrollbar;`]
4. Uniform naming conventions ，less character
5. don't use network fonts, many area  invite slowly.
6. bootstrap and jquery don't use cdn library , use bower  local file

Thank you!

**Comment by rafael-renan-pacheco** [comment]
A List component/widget would be lovely. Tables don't work very well on mobile.

Here is an example: https://www.google.com/design/spec/components/lists.html#lists-usage

**Comment by YasserHassan** [comment]
Full support of events such as at right sidebar expand/collapse, boxes expand/collapse, maybe menus show/hide ...etc to have standard documented events that developers can use to in their projects.

**Comment by enumag** [comment]
It seems that bootstrap 4 will have two variants - standard variant with grid similar to what we know from BS3 and a second variant with grid system made entirely using flexbox. Which one are you plannig to use in AdminLTE 3? (I prefer flexbox.)
